#基础信息
title: kun的博客
email: 411241127@qq.com
url: wangbokun.com
avatar: assets/public/touxiang.png
description: 一个安静的程序猿

#文档配置
markdown: kramdown
kramdown:
  input: GFM
  extensions:
    - autolink
    - footnotes
    - smart

#高亮配置
highlight-theme : my-github

#评论配置
disqus: 

#统计配置
baidu: 


