#基础信息
title: kun的博客
email: 411241127@qq.com
url: wangbokun.com
avatar: assets/public/touxiang.png
description: 一个安静的程序猿

#文档配置
markdown: kramdown
kramdown:
  input: GFM
  extensions:
    - autolink
    - footnotes
    - smart

#高亮配置
highlight-theme : my-github

#评论配置
disqus: 

#统计配置
baidu: 


#菜单
menu:
  首页: / 
  前端: /categories/前端
  后端: /categories/后端
  理科: /categories/理科
  经济: /categories/经济
  生活: /categories/生活